#!/usr/bin/env bash
#Displays info about my domain and subdomains

subdomains=("www" "lib-01" "web-01" "web-02")

info () {
    dig $1 +noall +answer | awk -v prefix="$2" '{ print "This subdomain", prefix, "is a", $4, "record and points to", $5 }'
    return 0
}

i=0

if [ $# -eq 1 ];
then
    for subdomain in "${subdomains[@]}";
    do
        info "${subdomain}.$1" "${subdomain}"
    done
else
    info "$2.$1" "$2"
fi

