#!/usr/bin/env bash
# Installs Nginx and modifies the nginx config file
apt-get -y  update
apt-get -y install nginx
echo 'Hello World!' > /hello_world.txt
sed -i 's|root.*|root /|' -e 's|index.*|index hello_world.txt|' /etc/nginx/sites-available/default
service nginx restart
