#!/usr/bin/env bash
#Permanently redirects the page at /redirect_me to another page

apt-get -y  update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i "s/^[^#].*server_name.*/server_name _;\nrewrite ^\/redirect_me \/ permanent;/" /etc/nginx/sites-available/default
service nginx restart
