#!/usr/bin/env bash
#This script installs and configures Nginx to return a custome header

apt-get update
apt-get install nginx
sed -i 's|^[^#].*try_files $uri $uri/ =404;|\t\ttry_files $uri $uri/ =404;\n\t\tadd_header X-Served-By $hostname;|' /etc/nginx/sites-available/default
sed -i 's|localhost|localhost persistent-hostname|' /etc/hosts
hostnamectl set-hostname persistent-hostname
service nginx start
