#!/usr/bin/env bash
#Installs and configures HAProxy load balancer

apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get -y install haproxy=2.0.\*
echo -e 'frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\nbackend web-backend\n\tbalance roundrobin\n\tserver web1 100.25.156.15 check\n\tserver web2 100.25.36.199 check' | sudo tee -a /etc/haproxy/haproxy.cfg
service haproxy start
