#!/usr/bin/env bash
#Installs and configures HAProxy load balancer

apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y install haproxy=2.0.\*
echo -e '\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 218819-web-01 100.25.156.15:80 check\n\tserver 218819-web-02 100.25.36.199:80 check' >> /etc/haproxy/haproxy.cfg
service haproxy restart
