#!/usr/bin/env bash
#Generates a mysql dump and creates a compressed archive out of it

if [ $# -lt 2 ]
then
	mysqldump -u root -p "$1" --all-databases > backup.sql
	tar -czf "$(date '+%d-%m-%Y').tar.gz" backup.sql
fi
