#!/usr/bin/env bash
#creates a script to display its pid
#Displays "To infinity and beyond" infintely
#Handles SIGTERM and SIGINT, and SIGQUIT

function handler()
{
	rm /var/run/myscript.pid
	pkill -9 -f ./100-process_and_pid_file
}

pgrep -f ./100-process_and_pid_file > /var/run/myscript.pid

trap 'echo "Y U no love me?!"' SIGINT

trap 'handler' SIGQUIT
trap 'echo "I hate the kill command"; handler' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
