#!/usr/bin/env bash
# Displays numbers from 1 to 100
#+ If number is a multiple of 3 and 5 it displays 'FizzBuzz'
# If number is a multiple of 3, 'Fizz' is displayed
# If number is a multiple of 5, 'Buzz' is displayed

n=1

while [ $n -le 100 ]; do
	if ! (( n % 3 )) && ! (( n % 5 )); then
		echo "FizzBuzz"
	elif ! (( n % 3 )); then
		echo "Fizz"
	elif ! (( n % 5 )); then
		echo "Buzz"
	else
		echo "$n"
	fi

	(( n++ ))
done
