#!/usr/bin/env bash
# Displays 'bad luck' at the 4th iteration, 'good luck' at the 8th,
#+ and 'Best School' for the others.

i="0"

str1="Best School"
str2="bad luck"
str3="good luck"

while [ $i -lt 10 ]; do
	if [ $i -eq 3 ]; then
		echo "$str2"
	elif [ $i -eq 7 ]; then
		echo "$str3"
	else
		echo "$str1"
	fi
	
	(( i++ ))
done
