#!/usr/bin/env bash
# using case

i=1
str="bad luck from"

while [ $i -le 20 ]; do
	case $i in
		4)
			echo "$i"
			echo "$str China"
			;;
		9)
			echo "$i"
			echo "$str Japan"
			;;
		17)
			echo "$i"
			echo "$str Italy"
			;;
		*)
			echo "$i"
			;;
	esac

	(( i++ ))
done
